medius-group/medius-api

WebAPI/HttpREST/medius-openAPI.json, WebAPI/HttpREST/pay-EU-openAPI.json, WebAPI/HttpREST/pay-US-openAPI.json
Updates to pay and release payment
=> From master

WebAPI/HttpREST/s2c-openAPI.json
First version of openapi for source 2 contract
=> First version of openAPI

WebAPI/HttpREST/medius-openAPI.json
Synced changes applied in master to stable
=> Adjusted to align to Camel case and made item number mandatory on Purchase order

WebAPI/HttpREST/medius-openAPI.json
Added PreliminaryVoucherNumber and PreliminaryBookingDate fields
=> Updated referencedDocuments collection in IntegrationSupplierInvoiceDto

WebAPI/HttpREST/medius-openAPI.json, WebAPI/HttpREST/pay-EU-openAPI.json, WebAPI/HttpREST/pay-US-openAPI.json
Updated descriptions + payeeRoutingNumberType
=> Added invoicevoucher and payeeRoutingNumber - Pay

README.md, WebAPI/HttpREST/medius-openAPI.json
- Updated texts
- Added invoice voucher number
- Added payeeRoutingNumberType
=> Added new fields for pay

WebAPI/HttpREST/medius-openAPI.json
Added End date to accruals
Removed StartDate as required
Added descriptions for referencedDocuments
=> Changes to accruals and referencedDocuments

WebAPI/HttpREST/medius-openAPI.json
=> Authorizationgroupimport support

.github/workflows/validate-oas.yml, WebAPI/HttpREST/medius-openAPI.json, WebAPI/HttpREST/pay-EU-openAPI.json, WebAPI/HttpREST/pay-US-openAPI.json, WebAPI/HttpREST/s2c-openAPI.json
Pay: Add voucher number description and add preferred payment date for US.
S2C: authentication
=> Pay and S2C

.github/workflows/validate-oas.yml, WebAPI/HttpREST/medius-openAPI.json
Adding oneof schemas for US and EU
=> Mfdoc 1733 pay restructure

WebAPI/HttpREST/medius-openAPI.json
Move security to openAPI from azure function.
=> Add security

WebAPI/HttpREST/medius-openAPI.json
Move security to openAPI from azure function.
=> Add security to Master

WebAPI/HttpREST/medius-openAPI.json
`countryCode` added to company import API
`eInvoiceTrackingId` added to supplier invoice message and document import APIs.
=> Added two new fields

WebAPI/HttpREST/medius-openAPI.json
S2P-8934 - typo fix for nullable
=> S2P-8934 - typo fix for nullable

WebAPI/HttpREST/medius-openAPI.json
Add externalSystemMetaData to:
- Dimension value
- Payment terms
- Tax codes
- Tax groups
Added enum list and description to Type field in Restriction rule import.
=> Add externalsystemmetadata

WebAPI/HttpREST/medius-openAPI.json
Structure changes and Scope addition
=> Purchase order document corrections

WebAPI/HttpREST/medius-openAPI.json
Structural changes and scope addition
=> Purchase order document corrections to master

WebAPI/HttpREST/medius-openAPI.json
=> Correction externalSystemMetadata

WebAPI/HttpREST/medius-openAPI.json
=> Correction externalSystemMetadata to master

WebAPI/HttpREST/medius-openAPI.json
In addition, description will be removed from the azure function.
=> updated spec description

WebAPI/HttpREST/medius-openAPI.json
AddressInformation property to document import and supplier invoice message.
DocumentOriginalFormat field to document import.
=> Add addressInformation and documentOriginalFormat

WebAPI/HttpREST/medius-openAPI.json
- PrePayments added to document import and supplier invoice message
- AddressInformation added to document import and supplier invoice message
- DocumentOriginalFormat added to document import
=> Additions to master

WebAPI/HttpREST/medius-openAPI.json
- S2P-9906 - Add `AddressPairDto `for response
=> Supplier Management - Add AddressPairDto Dto

.github/workflows/validate-oas.yml, WebAPI/HttpREST/medius-openAPI.json, WebAPI/HttpREST/pay-EU-openAPI.json, WebAPI/HttpREST/pay-US-openAPI.json
SM - AddressPair
Pay - Vouchernumber not required
=> Updates to Stable
